name: Setup Python and Install Dependencies

on:
  push:
    branches: [ main ]  # replace `main` with your default branch if it's different

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install spacy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Purge pip cache
      run: |
        python -m pip cache purge
